version: '3'
services:
  dynu-updater:
    image: longkeyy/dynu-updater:1.1
    container_name: dynu-updater
    environment:
      - USERNAME=${USERNAME}
      - HASHED_PASSWORD=${HASHED_PASSWORD}
      - HOSTNAME={HOSTNAME}
    restart: unless-stopped
